# Generated by Django 3.2 on 2021-05-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('start', models.CharField(max_length=100)),
                ('end', models.DateField(max_length=100)),
                ('days', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
