# Generated by Django 3.2 on 2021-05-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='file_data',
            field=models.FileField(default='', upload_to='course_data'),
            preserve_default=False,
        ),
    ]
